### ISSUE TITLE
imdb.period problem in 2.1.6

### ISSUE THREAD

**Issue by voidzero** [MilhouseVH/texturecache.py#29]
<pre>
# ./texturecache.py 
Traceback (most recent call last):
  File "./texturecache.py", line 8215, in <module>
    main(sys.argv[1:])
  File "./texturecache.py", line 7919, in main
    loadConfig(argv)
  File "./texturecache.py", line 7428, in loadConfig
    gConfig = MyConfiguration(argv)
  File "./texturecache.py", line 408, in __init__
    self.IMDB_PERIOD = self.getValue(config, "imdb.period", None, allowundefined=True)
  File "./texturecache.py", line 576, in getValue
    if default is None and not allowNone:
NameError: global name 'allowNone' is not defined
</pre>

Looks like this can be worked around by setting imdb.period to some value. Not sure what, but 1 seems to work. :)

**Comment by MilhouseVH** [comment]
Thanks, can you confirm if 2.1.7 is OK? The perils of scripted languages...that's been undefined for almost 2 years and just waiting for someone to fall over it. :)

**Comment by voidzero** [comment]
*grin*

Yep, works properly now. Thank you!
