### ISSUE TITLE
Re-cache artwork option does not work when not supplying a filter and using setting "allow.recacheall = yes".

### ISSUE THREAD

**Issue by RWCHRISTIAANSE** [MilhouseVH/texturecache.py#37]
Hi.

I try to recache all my movies. 

In texturecache.cfg I have added the next line:

allow.recacheall = yes

This is the command I ran:

texturecache.py C movies

And this is the result:

Traceback (most recent call last):
  File "C:\Dev\Projects\texturecache.py-master\texturecache.py", line 8578, in <module>
    main(sys.argv[1:])
  File "C:\Dev\Projects\texturecache.py-master\texturecache.py", line 8278, in main
    if not checkConfig(argv[0]): sys.exit(2)
  File "C:\Dev\Projects\texturecache.py-master\texturecache.py", line 7818, in checkConfig
    data = wcomms.sendJSON(REQUEST, "libPing", checkResult=False, useWebServer=True)
  File "C:\Dev\Projects\texturecache.py-master\texturecache.py", line 2200, in sendJSON
    return self.sendWeb("POST", "/jsonrpc", id, request, {"Content-Type": "application/json"}, timeout=timeout)
  File "C:\Dev\Projects\texturecache.py-master\texturecache.py", line 2187, in sendWeb
    return json.loads(data) if data != "" else ""
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python35-32\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python35-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python35-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Is this a bug or am I doing something wrong?

Greetz,
Robert

**Comment by MilhouseVH** [comment]
Whatever web server you're connecting to isn't the Kodi web server, and is returning a non-JSON response. Check which port the Kodi web server is listening on, and if it's not the default port (which is 8080) then you'll need to add the port to texturecache.cfg with `webserver.port=####`.

**Comment by RWCHRISTIAANSE** [comment]
Grrr, how dumb of me. Changed it and it works now. Thank you for swift reply.
