### ISSUE TITLE
Seems to crash Odroid C2 - Libreelec

### ISSUE THREAD

**Issue by danmed** [MilhouseVH/texturecache.py#42]
On the latest revision - 7.90.008 running texturecache.py to cache artwork seems to completely hang the device after a short period of time.

Seems to throw a JSON error and then SSH and Gui are dead. (although sometimes it hangs without throwing the error pasted below)

Anyway i can track down what's doing this to be able to provide you with something more useful?

Here is the screen output : 

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "./texturecache.py", line 1097, in run
    if not self.loadImage(item) and not item.missingOK:
  File "./texturecache.py", line 1170, in loadImage
    (url, rowexists) = self.geturl(item)
  File "./texturecache.py", line 1116, in geturl
    url = self.json.getDownloadURL(item.filename)
  File "./texturecache.py", line 2741, in getDownloadURL
    data = self.sendJSON(REQUEST, "preparedl")
  File "./texturecache.py", line 2208, in sendJSON
    return self.sendWeb("POST", "/jsonrpc", id, request, {"Content-Type": "application/json"}, timeout=timeout)
  File "./texturecache.py", line 2142, in sendWeb
    web.request(request_type, url, sdata, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
  File "/usr/lib/python2.7/httplib.py", line 859, in send
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
error: [Errno 111] Connection refused

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "./texturecache.py", line 1097, in run
    if not self.loadImage(item) and not item.missingOK:
  File "./texturecache.py", line 1170, in loadImage
    (url, rowexists) = self.geturl(item)
  File "./texturecache.py", line 1116, in geturl
    url = self.json.getDownloadURL(item.filename)
  File "./texturecache.py", line 2741, in getDownloadURL
    data = self.sendJSON(REQUEST, "preparedl")
  File "./texturecache.py", line 2208, in sendJSON
    return self.sendWeb("POST", "/jsonrpc", id, request, {"Content-Type": "application/json"}, timeout=timeout)
  File "./texturecache.py", line 2142, in sendWeb
    web.request(request_type, url, sdata, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
  File "/usr/lib/python2.7/httplib.py", line 859, in send
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
error: [Errno 111] Connection refused

**Comment by MilhouseVH** [comment]
It's an instability in the Odroid build, either network stack or kernel.

It's been reported on the forum (LE and Kodi forums, if memory serves) so you're not the only one seeing this, but it should be reported to the Odroid maintainers as this script is simply triggering the issue.

This script can work the system very hard with `kodi.bin` rescaling/caching artwork - typically a combination of CPU, GPU and network - while the script itself is doing very little other than waiting for `kodi.bin` to respond to a small webserver request. It's this combined high load that is causing the device to lock up when it shouldn't.

If you have a different network connection (ie. WiFi dongle) then try that as it may eliminate the wired network stack (which I assume you are using). If it doesn't crash with a different network stack then it's potentially useful information for the Odroid maintainers.

You could also try using fewer download threads to try and reduce the system load - add `@download.threads=1` (default is 2) to your command line/config.

**Comment by danmed** [comment]
Thanks for the reply, I hadn't thought of trying wireless so i will do that when i find a dongle.

The threads don't make a difference unfortunately.. Sometimes i can get thousands of images, other times i only get 5 before it craps out.

Thanks again for the advice.

**Comment by danmed** [comment]
I may have resolved this issue.. atleast the hanging of the device anyway..

My Database is MySQL and was getting a bit crufty so i blew it away and started afresh.. So far i'ts grabbed over 1000 images and it's still going strong!

**Comment by MilhouseVH** [comment]
This should now be [fixed in LibreELEC](https://github.com/LibreELEC/LibreELEC.tv/pull/1286). It was actually a memory fragmentation issue affecting 64-bit systems such as the Odroid C2 but also x86_64.

However you'd be less likely to see the issue on x86_64 as such systems typically have multiple gigabytes of spare RAM. Systems with less RAM, eg. Odroid C2, would experience it more often.

This script simply acted as a convenient way to trigger the issue. Thanks for reporting.
