### ISSUE TITLE
"No JSON object could be decoded"

### ISSUE THREAD

**Issue by raspdealer** [MilhouseVH/texturecache.py#46]
Launching the following cmd was working in the past but now I have this error
>> ./texturecache.py c video

```
Traceback (most recent call last):
  File "./texturecache.py", line 8618, in <module>
    main(sys.argv[1:])
  File "./texturecache.py", line 8311, in main
    if not checkConfig(argv[0]): sys.exit(2)
  File "./texturecache.py", line 7851, in checkConfig
    data = wcomms.sendJSON(REQUEST, "libPing", checkResult=False, useWebServer=True)
  File "./texturecache.py", line 2223, in sendJSON
    return self.sendWeb("POST", "/jsonrpc", id, request, {"Content-Type": "application/json"}, timeout=timeout)
  File "./texturecache.py", line 2210, in sendWeb
    return json.loads(data) if data != "" else ""
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
Any suggestion?

**Comment by raspdealer** [comment]
Changing port from 80 to 8080 fixed it
